### ISSUE TITLE
RF processing of Zarr content to go straight from s3

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#155]
Going through dandi api had shown to be slowish, still needing interaction with S3 anyways, filling up dandi archive logs https://github.com/dandi/dandi-archive/issues/1094 . Let's archive by crawling S3 bucket for that Zarr prefix directly.
- datalad-crawler simple_s3 pipeline could have been used, and it would have taken care about versioned URLs etc, but it would not be able to mint annex key without downloading content ATM which is our feature here
- by going through s3 we might end up getting the state different from what dandi-api server knows about in its checksummed state. We might need some fsck functionality/command to ensure consistency. As such we wouldn't be able to rely on using overall Zarr folder hash, or later tree hashes

With the latter in mind, ideally RF shouldn't strip all current functionality but may be at least theoretically allow for two modes of operation, in case we decide to go back to some improved dandi API? But I guess that is optional and we could just revert later if there would be some strong need

**Comment by jwodder** [comment]
For comparison: A run of the current, Dandi Archive-based code (commit a48ca6c) for backing up Dandiset 000108 from scratch ran for 7239m 57.293s (just over 5 days) before dying due to the following URLs (with query parameters stripped) all returning 404:

* https://dandiarchive.s3.amazonaws.com/zarr/b5ff7c36-1f2b-4205-838a-1666c53d0ad8/info
* https://dandiarchive.s3.amazonaws.com/zarr/b6a86a44-27ce-406c-926e-428df759af2e/info
* https://dandiarchive.s3.amazonaws.com/zarr/d4d72958-fb74-4b30-a323-5f98f85ba5ee/info
* https://dandiarchive.s3.amazonaws.com/zarr/f4bbb881-dc02-4003-ad7c-590176dc2c0f/info
* https://dandiarchive.s3.amazonaws.com/zarr/12c62295-6476-4390-9ea6-5a5835a777b8/info

(Examining one of the Zarrs in the API showed that there was an "info" file listed in the root directory, but trying to access it still returned a 404.  This is likely a synchronization problem in the Archive.)

During those five days, 432 Zarrs (out of 3088, according to an API query at this moment) were backed up.

**Comment by yarikoptic** [comment]
Attn @satra on above that some zarrs might have access issues

**Comment by satra** [comment]
different archives may have the `info` file, but they technically should not exist. depending on stage of cleanup, they may have been removed. where are you getting list of files from?

**Comment by satra** [comment]
also see this issue: https://github.com/dandi/dandi-archive/issues/1091

(there is no way currently for me to force reingest, which is possibly related to these issues).

**Comment by jwodder** [comment]
@satra Currently, I'm getting the list of files from the Dandi Archive API.  See, for example, https://api.dandiarchive.org/api/zarr/12c62295-6476-4390-9ea6-5a5835a777b8.zarr/, which includes an "info" item.
