### ISSUE TITLE
Q: we are ignoring all? errors from external annex processes?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#194]
Was thinking to look into all those reported errored exits from whereis, while our backup process continued. warning was reported from
https://github.com/dandi/dandisets/blob/draft/tools/backups2datalad/util.py#L141 
point.  There seems to be no exception raising at all, and I wondered why?  are we continuing to operate on any external process failure upon exit and should not it be fixed to "error out" by default and only in specific cases to ignore such errors since generally processes should exit normally?

**Comment by jwodder** [comment]
@yarikoptic If you're specifically referring to errors from `git-annex whereis`, those happen whenever it's passed a key that hasn't yet been registered in git-annex, which happens during normal operation.

**Comment by yarikoptic** [comment]
`whereis` is indeed the majority of those cases.
-  We should not issue a warning where it is "normal operation" -- it is misguiding etc.
- same warning seems to be issued for some addurls
 
```
(base) dandi@drogon:/mnt/backup/dandi/dandisets/000108/.git/dandi/logs$ grep -v whereis /tmp/exited-returncode
sync-20211228133824Z-1156.log:2021-12-31T21:38:11-0500 [WARNING ] backups2datalad git-annex addurl command exited with return code 1
sync-20220525190756Z-2200413.log:2022-05-25T20:43:50-0400 [WARNING ] backups2datalad git-annex addurl command exited with return code 1
sync-20220531185804Z-1923684.log:2022-05-31T17:52:22-0400 [WARNING ] backups2datalad git-annex addurl command exited with return code 1
sync-20220607190601Z-3630790.log:2022-06-07T16:07:42-0400 [WARNING ] backups2datalad git-annex addurl command exited with return code 1
sync-20220607202517Z-3784407.log:2022-06-07T21:05:31-0400 [WARNING ] backups2datalad git-annex addurl command exited with return code 1
sync-20220608010643Z-56925.log:2022-06-07T22:17:30-0400 [WARNING ] backups2datalad git-annex addurl command exited with return code 1
```
are those also "normal"?

**Comment by jwodder** [comment]
@yarikoptic No, those aren't normal.

**Comment by yarikoptic** [comment]
> @yarikoptic No, those aren't normal.

so the process then should error out after... and interestingly it seems to typically error out... these days immediately with `git gc` error but before it were some others as well.  [here](http://www.onerussian.com/tmp/after-return-code-all.txt) is the output from  `grep -A1000 ' backups2datalad git-annex addurl command exited with return code 1' *.log` within 000108 logs.  Interestingly one sync-20220531185804Z-1923684.log seems to proceed forward (before I disabled pushing data?) even after that error. But it is only one... thus it isn't clear if we would error out if addurls fail, and either that `git gc` erroring out has to do anything with `addurls` erroring out

**Comment by jwodder** [comment]
@yarikoptic I'm assuming that `git-annex addurl` exits nonzero iff a file failed to download, i.e., if `"success"` was `false` for some result record output by `addurl`.  Whenever the latter event happens, the backup script currently just marks down the file as a failed download (though #199 will change that a bit) and continues processing the remaining assets.  It is only after all assets (including Zarrs) are synced that the script checks whether there were any failed downloads and, if there were, it raises a `RuntimeError`.

Looking at the logs you posted, all of the entries that don't end in a `RuntimeError` are due to an error occuring while syncing a Zarr, which is a separate subroutine of the Dandiset backups (the latter being the part that actually uses addurl):

* The `git gc` errors are from Zarr syncs.
* The `FileNotFoundError` seems to have occurred because a Zarr backup lacked a `.dandi` directory (likely due to having originally been created before that directory was added to the code).
* I'm not entirely sure what happened with the entry with all the "error listing: directory not found" lines; the traceback indicates it happened while pushing a Zarr dataset to GitHub, but the CommandError from datalad says it was running `git -c diff.ignoreSubmodules=none annex copy --batch -z --to dandi-dandizarrs-dropbox --jobs 5 --fast --json --json-error-messages --json-progress -c annex.dotfiles=true`; why would pushing to GitHub make DataLad copy to Dropbox?

**Comment by yarikoptic** [comment]
> It is only after all assets (including Zarrs) are synced that the script checks whether there were any failed downloads and, if there were, it raises a `RuntimeError`.

whenever it makes sense to spend time to initiate and populate zarrs while delaying issuing the error, it probably makes little sense to proceed with other urls only then to fail without commit since we would need to `git annex reset --hard` and retry the process to ensure that we get it right.

the other issues I guess might have been handled (e.g. `git gc` errors we dealt with I believe)

**Comment by jwodder** [comment]
@yarikoptic So you're saying that a Dandiset backup should fail immediately if an error occurs while downloading/registering a URL with git-annex?  Should this only happen for `addurl` calls (which are only used for downloading files that aren't annexed, i.e., text files in Dandisets) or also for `registerurl` calls (used for binary files in Dandisets and all files in Zarrs)?

**Comment by yarikoptic** [comment]
I think so.  I think it should happen to any call which at the end of the process currently would result in an error of an overall dandiset backup run and I think both of those would, wouldn't they?

**Comment by jwodder** [comment]
@yarikoptic Actually, only failed `addurl` calls result in a failed backup.  Failed `registerurl` calls just result in an ERROR-level log message and nothing else, though there is a "TODO: Raise an exception?" comment in the code there.

Also, for completeness, it appears that calls to `git-annex fromkey` can fail as well (or at least the returned JSON has a "success" key), though I don't know when that would happen, and any failures there are currently responded to the same way as for `registerurl`.
